import {
  FaAndroid, FaApple, FaReact, FaCode, FaRobot, FaBrain,
  FaShoppingCart, FaCloud, FaCogs, FaGlobe, FaLayerGroup,
  FaComments, FaCubes, FaChartLine, FaBitcoin,
  FaUserTie, FaGraduationCap, FaStore, FaWallet,
  FaMicrochip, FaHandshake, FaCar, FaUtensils,
  FaHeartbeat, FaDesktop, FaWordpressSimple, FaShopify,
  FaLaravel, FaNodeJs, FaSearch, FaLock, FaRocket,
  FaTools, FaCreditCard, FaLink, FaBox,
  FaHome, FaStar, FaBook, FaGamepad, FaPaw, FaChartBar,
  FaAws, FaServer, FaDatabase, FaExchangeAlt, FaMoneyBillWave,
  FaHospital, FaIndustry, FaBroadcastTower, FaLaptop,
  FaEdit, FaClipboard, FaTh, FaFire, FaClock, FaAngular, FaPhp,
  FaJava, FaChartArea, FaRegMoon, FaPlug,
} from "react-icons/fa";
import { SiNextdotjs, SiFlutter, SiSolidity, SiTensorflow, SiSalesforce } from "react-icons/si";
import { MdWeb, MdSmartphone, MdPayment, MdSecurity, MdRefresh, MdOutlineScience } from "react-icons/md";
import { BsGpuCard, BsLightningCharge, BsGear, BsEye, BsGraphUp, BsCloudFill, BsBuilding } from "react-icons/bs";
import { GiFactory } from "react-icons/gi";
import { HiOutlinePuzzle } from "react-icons/hi";

const iconMap = {
  // tech platforms
  android: FaAndroid,
  apple: FaApple,
  react: FaReact,
  code: FaCode,
  robot: FaRobot,
  brain: FaBrain,
  smartphone: MdSmartphone,
  globe: FaGlobe,
  world: FaGlobe,
  gpu: BsGpuCard,
  lightning: BsLightningCharge,
  gear: BsGear,
  nextjs: SiNextdotjs,
  layers: FaLayerGroup,
  laravel: FaLaravel,
  wordpress: FaWordpressSimple,
  shopify: FaShopify,
  cart: FaShoppingCart,
  nodejs: FaNodeJs,
  web: MdWeb,
  cloud: FaCloud,
  cloudFill: BsCloudFill,
  erp: FaCogs,
  handshake: FaHandshake,
  graduation: FaGraduationCap,
  desktop: FaDesktop,
  laptop: FaLaptop,
  chat: FaComments,
  tensorflow: SiTensorflow,
  eye: BsEye,
  chip: FaMicrochip,
  search: FaSearch,
  solidity: SiSolidity,
  cubes: FaCubes,
  chart: FaChartLine,
  bitcoin: FaBitcoin,
  azure: FaCloud,
  aws: FaAws,
  salesforce: SiSalesforce,
  usertie: FaUserTie,
  food: FaUtensils,
  car: FaCar,
  store: FaStore,
  wallet: FaWallet,
  heart: FaHeartbeat,
  flutter: SiFlutter,
  lock: FaLock,
  keylock: FaLock,
  rocket: FaRocket,
  tools: FaTools,
  payment: MdPayment,
  link: FaLink,
  box: FaBox,
  home: FaHome,
  book: FaBook,
  game: FaGamepad,
  paw: FaPaw,
  bar: FaChartBar,
  graphUp: BsGraphUp,
  security: MdSecurity,
  creditcard: FaCreditCard,
  star: FaStar,
  server: FaServer,
  database: FaDatabase,
  exchange: FaExchangeAlt,
  money: FaMoneyBillWave,
  hospital: FaHospital,
  factory: GiFactory,
  broadcast: FaBroadcastTower,
  edit: FaEdit,
  palette: FaStar,
  refresh: MdRefresh,
  scroll: FaClipboard,
  bank: FaMoneyBillWave,
  trending: BsGraphUp,
  flask: MdOutlineScience,
  clipboard: FaClipboard,
  predict: BsGraphUp,
  java: FaJava,
  angular: FaAngular,
  php: FaPhp,
  mobile: MdSmartphone,
  build: BsBuilding,
  plug: FaPlug,
  clock: FaClock,
  halfclock: FaClock,
  fire: FaFire,
  puzzle: HiOutlinePuzzle,
};

export function ServiceIcon({ name, className = "w-6 h-6" }) {
  const Comp = iconMap[name] || FaCode;
  return <Comp className={className} />;
}

export default iconMap;
